export const SET_COURSE_LIST = "SET_COURSE_LIST"

export const SET_SEARCH_COURSE_LIST = "SET_SEARCH_COURSE_LIST"

export const SET_USER_LIST = "SET_USER_LIST"

export const SET_SEARCH_USER_LIST = "SET_SEARCH_USER_LIST"