export const ADD_COURSE = "ADD_COURSE"

export const DROP_COURSE = "DROP_COURSE"

export const SET_CGPA = "SET_CGPA"

export const SET_CREDITS_EARNED = "SET_CREDITS_EARNED"

export const RESET_CALCULATE = "RESET_CALCULATE"